# config/application.yml
defaults: &defaults
  user: admin
  admin_emails: ["test@example.com"]

development:
  <<: *defaults
  password: secret

test:
  <<: *defaults
  password: test
  admin_emails: ["test@example.com"]

production:
  <<: *defaults
  password: change_me
