---
# This is the TorqueBox configuration file. Refer to the TorqueBox
# documentation at http://torquebox.org/documentation/current/ 
# for all configuration options.
web:
  context: "/"
tasks:
  Backgroundable:
    concurrency: 4
jobs:
  concurrency: 1
  mail_notifier:
    job: MailNotifier
    cron: '0 1 1 * * ?'
    timeout: 2 m
    description: Deliver queued mail notifications

